<a href="https://colab.research.google.com/github/ckrickyh/pythonTools/blob/main/TMCP_F2_DataSummarization_Ver4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import geopandas as gpd
import pandas as pd
import json
import xlwings as xw
import zipfile
import pathlib
import numpy as np
from pathlib import Path

In [ ]:
folderpath = input('e.g. L:\LU\TRAM 10 Form 2\Batch 2\Done_zip,pdf,attachment')

e.g. L:\LU\TRAM 10 Form 2\Batch 2\Done_zip,pdf,attachment L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT

# Interal docPath Setting

In [ ]:
CSV2Masterjsondata = r'C:\TMCP\CSVToMasterValue.json'
tmcpCSVpath = r'C:\TMCP\CSVUnZIPTemp'

#Export Result location
xlExportPath = r'C:\Users\ckho\Desktop\tmcp\tram10f2summary.xlsx' #小心, 這FILE 以f2 TARGET NO. 做BASE (不是 F2 TREE ID 做 BASE), 所以DATA 會 多於一個 TREE ID
xlErrPath = r'C:\Users\ckho\Desktop\tmcp\tram10f2errzip.xlsx'

# Null setting

In [ ]:
df_f2basicAll = []
count = 0
num = 0
d = None
d = {}
dall = None
dall = {}
fllist =[]

# Read CSVtoMasterValue json

In [ ]:
#CSV2Masterjsondata = r'C:\TMCP\CSVToMasterValue.json'

pathlist = str(Path(CSV2Masterjsondata).parent)
pathlist

with open(CSV2Masterjsondata) as f:
    json_data = f.read()
    data = json.loads(json_data)
    #print(data)
    df_csv = pd.json_normalize(data)

df_csv['link'] = pathlist + '\\' +df_csv['FileName']
df_csv.head()

,FileName,MasterType,IsSystem,link
0,TBL_ADVANCED_ASSESSMENT.csv,AdvancedAssessment,false,C:\TMCP\TBL_ADVANCED_ASSESSMENT.csv
1,TBL_ASPECT.csv,Aspect,false,C:\TMCP\TBL_ASPECT.csv
2,TBL_AUDITOR.csv,,false,C:\TMCP\TBL_AUDITOR.csv
3,TBL_CONTRACT.csv,,False,C:\TMCP\TBL_CONTRACT.csv
4,TBL_CROWN_DENSITY_PERCENT.csv,CrownDensityD,false,C:\TMCP\TBL_CROWN_DENSITY_PERCENT.csv

# Read CSV decoding

In [ ]:
#tmcpCSVpath = r'C:\TMCP\CSVUnZIPTemp'

#create dataframe blank in dic
dCsv=None
dCsv={}

path = pathlib.Path(tmcpCSVpath)
files = path.glob("**/TBL*.csv")

#codetablelist
for i in files:
    dCsv[i.stem + i.suffix] = pd.read_csv(i, sep='\t')
dCsv.keys()

dict_keys(['TBL_ADVANCED_ASSESSMENT.csv', 'TBL_ASPECT.csv', 'TBL_AUDITOR.csv', 'TBL_CONTRACT.csv', 'TBL_CROWN_DEFOLIATION_PERCENT.csv', 'TBL_CROWN_DENSITY_PERCENT.csv', 'TBL_CROWN_DIEBACK.csv', 'TBL_CROWN_FOLIAGE.csv', 'TBL_CROWN_LEAF_SIZE.csv', 'TBL_CROWN_LIVE_CROWN.csv', 'TBL_CROWN_LOAD.csv', 'TBL_CROWN_LOAD_DENSITY.csv', 'TBL_DEPARTMENT.csv', 'TBL_DISTRICT.csv', 'TBL_FAILURE_STATUS.csv', 'TBL_FAILURE_TYPE.csv', 'TBL_INSPECTION_FREQUENCEY.csv', 'TBL_INSPECTION_TIME.csv', 'TBL_INSPECTOR.csv', 'TBL_IRRIGATION.csv', 'TBL_LOCATION_TYPE.csv', 'TBL_MASTER_ZONE.csv', 'TBL_MITIGATION_MEASURE.csv', 'TBL_PEST_DISEASE.csv', 'TBL_PRUN_LION.csv', 'TBL_PRUN_REDUCTION.csv', 'TBL_REMEDIAL_ACTION.csv', 'TBL_RESIDUAL_RISK.csv', 'TBL_RESTRICTION_DRIPLINE.csv', 'TBL_RISK_CONSEQUENCE.csv', 'TBL_RISK_FAILURE.csv', 'TBL_RISK_FAILURE_IMPACT.csv', 'TBL_RISK_IMPACT.csv', 'TBL_RISK_RATING.csv', 'TBL_RISK_RATING_MATRIX.csv', 'TBL_ROOT_CONDITION.csv', 'TBL_ROOT_FAILURE_TYPE.csv', 'TBL_ROOT_FUNGAL.csv', 'TBL_SLOPE_RANGE.csv', 'TBL_SOIL_COMPOSITION.csv', 'TBL_SOIL_MOISTURE.csv', 'TBL_SUBZONE.csv', 'TBL_TARGET_DESC.csv', 'TBL_TARGET_OCCUPANCY.csv', 'TBL_TARGET_ZONE.csv', 'TBL_TREE_CONDITION.csv', 'TBL_TREE_INVENTORY.csv', 'TBL_TREE_PART.csv', 'TBL_TREE_RISK_MANAGEMENT_ZONE.csv', 'TBL_TREE_SPECIES.csv', 'TBL_TREE_STATUS.csv', 'TBL_TRIAGE_COLOUR.csv', 'TBL_VIGOR.csv', 'TBL_WIND.csv'])

# Read zip

In [ ]:
fllist =[]
errlist =[]

#folderpath = r'C:\Users\ckho\Desktop\trialtmcp'
path = Path(folderpath)
files = path.glob("**/*.zip")

for zip in files:
    fllist.append(zip)

for zip in fllist:
    print('File. ' + str(num+1) + ' / ' + str(len(fllist)))
    print(zip)

    try:
        with zipfile.ZipFile(zip, "r") as z:
            print(z.namelist())

            for filename in z.namelist():
                print('z: ' + filename)


                #===========================================================================================database and f2
                #if 'json' in filename and 'Version' in filename and '/' not in filename:      #===========read version and mapping database
                if 'VersionAndMapping.json' in filename:
                    f2 = filename
                    jsondata = f2
                    print(f2)

                    pathlist = str(Path(jsondata).parent)

                    with z.open(jsondata) as f:
                        json_data = f.read()
                        datameta = json.loads(json_data)
                        print('Y')
                        #print(datameta)
                        #df_summary = pd.json_normalize(datameta)

                        df_dbmasterValue = pd.json_normalize(datameta, record_path = ['masterValueList'])  #=======gen version and mapping, Read mastervaluelist data, then lookup

                        #cb clickbox
                        df_decode1 = df_dbmasterValue[df_dbmasterValue.Code.str.startswith('cb')]
                        df_decode1 = df_decode1.rename(columns={"Code": "Result", "MasterTypeCode": "Code"})
                        #df_decode1.head()

                        #form2.SoilCrackOrCrackBehindLean
                        #form2.Status
                        otherlist = ['SCOrCBLean','Status']
                        df_decode2 = df_dbmasterValue[(df_dbmasterValue.MasterTypeCode.isin(otherlist))]
                        df_decode2 = df_decode2.rename(columns={"Code": "Result", "MasterTypeCode": "Code"})
                        #df_decode2.head()

                        #Merge df_dbmasterValue and df_csv  dataset
                        dflink = pd.merge(df_dbmasterValue,df_csv, left_on='MasterTypeCode', right_on='MasterType')
                        ##dflink['Code'].astype(str)
                        #dflink.head()

                        #Decoding Mapping and Version recorded in 'Result Column'
                        resultlist = []
                        for index, row in dflink.iterrows():
                            #print(row['Code'])
                            selectData = [int(row['Code'])]
                            #print(dCsv[row["FileName"]])
                            dfa = dCsv[row["FileName"]]
                            dfacode = dCsv[row["FileName"]]['CSV_CODE']
                            result = dfa[(dfacode.isin(selectData))].iloc[0,3]
                            resultlist.append(result)
                            #df2[(df2['ID'].isin(df1['ID']))]

                        dflink['Result'] = resultlist

                        dflink = pd.concat([dflink, df_decode1, df_decode2], ignore_index=True)   #Decoding
                        #dflink


                        #============== 全區tree dot 地圖, read treelist , use "ID" connect TreeID, DEPTTreeID, SpeciesCode, SpeciesTypeCode, MasterZoneID, SubZoneID, TriageColourCode, TriageColourTypeCode, X, Y, isNewTree
                        df_dbtreeList = pd.json_normalize(datameta, record_path = ['treeList'])

                #============================================================================================f2
                elif 'F2' in str(filename) and '.json' in str(filename): #===================read f2
                    f2 = filename
                    jsondata = f2
                    print('Y2')
                    print(jsondata)

                    with z.open(jsondata) as f:
                        json_data = f.read()
                        data = json.loads(json_data)
                        #print(data)
                        df_f2 = pd.json_normalize(data)

                        #==============================================================================F2 Basic infomation
                        f2basiclist =  df_f2.columns.to_list()[18:] #===========F2 Basic infomation

                        df_f2basic = df_f2[f2basiclist].replace(dflink.ID.tolist(),  dflink.Result.tolist())
                        #df_f2basic

                        TreeID = df_f2basic['form2.DEPTTreeID'].iloc[0] #========get TreeID
                        #X = df_f2basic['form2.CoordinateX'].iloc[0] #========get X
                        #Y = df_f2basic['form2.CoordinateY'].iloc[0] #========get Y
                        OverallComment = df_f2basic['form2.MitigationMeasureRemark'].iloc[0] #========get Comment
                        TMCPTreeID = pd.DataFrame(df_f2basic['form2.TreeGUID']).replace(df_dbtreeList.ID.tolist(),  df_dbtreeList.TreeID.tolist())['form2.TreeGUID'].iloc[0] #========get TMCPTreeID
                        print(TMCPTreeID)


                        #df_f2basicAll = []   #=========empty f2basicall
                        #count = 0
                        if count == 0:
                            df_f2basicAll = pd.DataFrame(columns = df_f2basic.columns.tolist())
                        df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
                        #print(df_f2basicAll)




                        #==============================================================================f2 advance infomation with decoding , link with csv
                        #num = 0

                        #create dataframe blank in dic
                        d = None
                        d = {}

                        f2sectionlist = df_f2.columns.to_list()[0:17]
                        #f2sectionlist.extend(['form2.TreeGUID'])

                        #codetablelist
                        for i in f2sectionlist:
                            d[i] = pd.json_normalize(data, record_path = [i])
                            d[i]['TreeID']=TreeID
                            #d[i]['X']=X
                            #d[i]['Y']=Y
                            d[i]['TMCPTreeID']=TMCPTreeID
                            d[i]['OverallComment']=OverallComment
                            d[i]['fldPath'] = str(zip)

                            #print(num)

                            ###Decoding
                            d[i] = d[i].replace(dflink.ID.tolist(),  dflink.Result.tolist())
                            #d[i] = d[i].replace(df_dbtreeList.ID.tolist(),  df_dbtreeList.TreeID.tolist()) #df_dbtreelist decode form2.TreeGUID

                            #Append gp
                            if num == 0:
                                dall[i] = pd.DataFrame(columns = d[i].columns.tolist())
                            dall[i] = pd.concat([dall[i],d[i]])


                            #d.keys()
                            #dall.keys()

            #=============================run 完一個 file 後
            count = count + 1
            num = num +1
    except:
        errlist.append(str(zip))
        pass

File. 1 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\ETR0610143\20250113163616_ETR0610143_11SW-A-R577_0_20241028.zip
['VersionAndMapping.json', 'F2_ETR0610143_11SW-A-R577_0_20241028/AUDIT/', 'F2_ETR0610143_11SW-A-R577_0_20241028/ETR0610143_11SW-A-R577_0_20241028.json', 'F2_ETR0610143_11SW-A-R577_0_20241028/VersionAndMapping.json', 'F2_ETR0610143_11SW-A-R577_0_20241028/MAP/map.png', 'F2_ETR0610143_11SW-A-R577_0_20241028/OTHER/20240429_ETR0610143_Photo.pdf', 'F2_ETR0610143_11SW-A-R577_0_20241028/OTHER/20241028_ETR0610143_Photo.pdf', 'F2_ETR0610143_11SW-A-R577_0_20241028/OTHER/after pruning in Nov 2024.png', 'F2_ETR0610143_11SW-A-R577_0_20241028/PHOTO/Profile.jpg', 'F2_ETR0610143_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_150957.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_ETR0610143_11SW-A-R577_0_20241028/AUDIT/
z: F2_ETR0610143_11SW-A-R577_0_20241028/ETR0610143_11SW-A-R577_0_20241028.json
Y2
F2_ETR0610143_11SW-A-R577_0_20241028/ETR0610143_11SW-A-R577_0_20241028.json
202403200001163
z: F2_ETR0610143_11SW-A-R577_0_20241028/VersionAndMapping.json
F2_ETR0610143_11SW-A-R577_0_20241028/VersionAndMapping.json
Y
z: F2_ETR0610143_11SW-A-R577_0_20241028/MAP/map.png
z: F2_ETR0610143_11SW-A-R577_0_20241028/OTHER/20240429_ETR0610143_Photo.pdf
z: F2_ETR0610143_11SW-A-R577_0_20241028/OTHER/20241028_ETR0610143_Photo.pdf
z: F2_ETR0610143_11SW-A-R577_0_20241028/OTHER/after pruning in Nov 2024.png
z: F2_ETR0610143_11SW-A-R577_0_20241028/PHOTO/Profile.jpg
z: F2_ETR0610143_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_150957.jpg
File. 2 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\ETR0610144\20250113165135_ETR0610144_11SW-A-R577_0_20241028.zip
['VersionAndMapping.json', 'F2_ETR0610144_11SW-A-R577_0_20241028/AUDIT/', 'F2_ETR0610144_11SW-A-R577_0_20241028/ETR0610144_11SW-A-R577_0_20241028.json', 'F2_ETR0610144_11SW-A-R577_0_20241028/VersionAndMapping.json', 'F2_ETR0610144_11SW-A-R577_0_20241028/MAP/map.png', 'F2_ETR0610144_11SW-A-R577_0_20241028/OTHER/20241204_ETR0610144_Photo.pdf', 'F2_ETR0610144_11SW-A-R577_0_20241028/PHOTO/Profile.jpg', 'F2_ETR0610144_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_153815.jpg', 'F2_ETR0610144_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_153820.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_ETR0610144_11SW-A-R577_0_20241028/AUDIT/
z: F2_ETR0610144_11SW-A-R577_0_20241028/ETR0610144_11SW-A-R577_0_20241028.json
Y2
F2_ETR0610144_11SW-A-R577_0_20241028/ETR0610144_11SW-A-R577_0_20241028.json
202403200001161

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_ETR0610144_11SW-A-R577_0_20241028/VersionAndMapping.json
F2_ETR0610144_11SW-A-R577_0_20241028/VersionAndMapping.json
Y
z: F2_ETR0610144_11SW-A-R577_0_20241028/MAP/map.png
z: F2_ETR0610144_11SW-A-R577_0_20241028/OTHER/20241204_ETR0610144_Photo.pdf
z: F2_ETR0610144_11SW-A-R577_0_20241028/PHOTO/Profile.jpg
z: F2_ETR0610144_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_153815.jpg
z: F2_ETR0610144_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_153820.jpg
File. 3 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\ETR0610145\20250113165856_ETR0610145_11SW-A-R577_0_20241028.zip
['VersionAndMapping.json', 'F2_ETR0610145_11SW-A-R577_0_20241028/AUDIT/', 'F2_ETR0610145_11SW-A-R577_0_20241028/ETR0610145_11SW-A-R577_0_20241028.json', 'F2_ETR0610145_11SW-A-R577_0_20241028/VersionAndMapping.json', 'F2_ETR0610145_11SW-A-R577_0_20241028/MAP/map.png', 'F2_ETR0610145_11SW-A-R577_0_20241028/OTHER/20241028_ETR0610145_Photo.pdf', 'F2_ETR0610145_11SW-A-R577_0_20241028/OTHER/after.jpg', 'F2_ETR0610145_11SW-A-R577_0_20241028/PHOTO/Profile.jpg', 'F2_ETR0610145_11SW-A-R577_0_20241028/PHOTO/Profile.png', 'F2_ETR0610145_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_151733.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_ETR0610145_11SW-A-R577_0_20241028/AUDIT/
z: F2_ETR0610145_11SW-A-R577_0_20241028/ETR0610145_11SW-A-R577_0_20241028.json
Y2
F2_ETR0610145_11SW-A-R577_0_20241028/ETR0610145_11SW-A-R577_0_20241028.json
202403200001164

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_ETR0610145_11SW-A-R577_0_20241028/VersionAndMapping.json
F2_ETR0610145_11SW-A-R577_0_20241028/VersionAndMapping.json
Y
z: F2_ETR0610145_11SW-A-R577_0_20241028/MAP/map.png
z: F2_ETR0610145_11SW-A-R577_0_20241028/OTHER/20241028_ETR0610145_Photo.pdf
z: F2_ETR0610145_11SW-A-R577_0_20241028/OTHER/after.jpg
z: F2_ETR0610145_11SW-A-R577_0_20241028/PHOTO/Profile.jpg
z: F2_ETR0610145_11SW-A-R577_0_20241028/PHOTO/Profile.png
z: F2_ETR0610145_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_151733.jpg
File. 4 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\ETR0610147\20250113171542_ETR0610147_11SW-A-R577_0_20241028.zip
['VersionAndMapping.json', 'F2_ETR0610147_11SW-A-R577_0_20241028/AUDIT/', 'F2_ETR0610147_11SW-A-R577_0_20241028/ETR0610147_11SW-A-R577_0_20241028.json', 'F2_ETR0610147_11SW-A-R577_0_20241028/VersionAndMapping.json', 'F2_ETR0610147_11SW-A-R577_0_20241028/MAP/map.png', 'F2_ETR0610147_11SW-A-R577_0_20241028/OTHER/20241028_ETR0610147_Photo.pdf', 'F2_ETR0610147_11SW-A-R577_0_20241028/OTHER/After.jpg', 'F2_ETR0610147_11SW-A-R577_0_20241028/PHOTO/Profile.jpg', 'F2_ETR0610147_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_152144.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_ETR0610147_11SW-A-R577_0_20241028/AUDIT/
z: F2_ETR0610147_11SW-A-R577_0_20241028/ETR0610147_11SW-A-R577_0_20241028.json
Y2
F2_ETR0610147_11SW-A-R577_0_20241028/ETR0610147_11SW-A-R577_0_20241028.json
202403200001162

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_ETR0610147_11SW-A-R577_0_20241028/VersionAndMapping.json
F2_ETR0610147_11SW-A-R577_0_20241028/VersionAndMapping.json
Y
z: F2_ETR0610147_11SW-A-R577_0_20241028/MAP/map.png
z: F2_ETR0610147_11SW-A-R577_0_20241028/OTHER/20241028_ETR0610147_Photo.pdf
z: F2_ETR0610147_11SW-A-R577_0_20241028/OTHER/After.jpg
z: F2_ETR0610147_11SW-A-R577_0_20241028/PHOTO/Profile.jpg
z: F2_ETR0610147_11SW-A-R577_0_20241028/PHOTO/TimePhoto_20241028_152144.jpg
File. 5 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033959\20250113172749_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028.zip
['VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/AUDIT/', 'F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028.json', 'F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/MAP/map.jpg', 'F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/OTHER/20241028_RTR0033959_Photo.pdf', 'F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/PHOTO/Profile.jpg', 'F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_144022.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/AUDIT/
z: F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028.json
Y2
F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028.json
202003200102402

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/VersionAndMapping.json
F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/MAP/map.jpg
z: F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/OTHER/20241028_RTR0033959_Photo.pdf
z: F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/PHOTO/Profile.jpg
z: F2_hyd_hk_11sw_a_r602_0_wt8_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_144022.jpg
File. 6 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033972\20250113174049_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028.zip
['VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/AUDIT/', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028.json', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/MAP/map.jpg', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/OTHER/20240430_RTR0033972_Photo.pdf', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033972_Photo.pdf', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/PHOTO/Profile.jpg', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20240429_125509.jpg', 'F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_133509.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/AUDIT/
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028.json
Y2
F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028.json
202003200092765

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/VersionAndMapping.json
F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/MAP/map.jpg
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/OTHER/20240430_RTR0033972_Photo.pdf
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033972_Photo.pdf
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/PHOTO/Profile.jpg
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20240429_125509.jpg
z: F2_hyd_hk_11sw_a_r614_0_wt2_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_133509.jpg
File. 7 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033979_abnormal density\RTR0033979_11SW-A-R614_0_20241028\RTR0033979_11SW-A-R614_0_20241028.zip
['VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/AUDIT/', 'F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028.json', 'F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/MAP/map.jpg', 'F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033979_Photo.pdf', 'F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/PHOTO/Profile.jpg', 'F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_131337.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/AUDIT/
z: F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028.json
Y2
F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028.json
202003200089522

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/VersionAndMapping.json
F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/MAP/map.jpg
z: F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033979_Photo.pdf
z: F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/PHOTO/Profile.jpg
z: F2_hyd_hk_11sw_a_r614_0_wt3_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_131337.jpg
File. 8 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033980\20250113180121_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029.zip
['VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/AUDIT/', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029.json', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/MAP/map.jpg', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/OTHER/20240429_RTR0033980_Photo.pdf', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/OTHER/20241028_RTR0033980_Photo.pdf', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/PHOTO/Profile.jpg', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/PHOTO/TimePhoto_20240429_140649.jpg', 'F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/PHOTO/TimePhoto_20241028_144628.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/AUDIT/
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029.json
Y2
F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029.json
202003200106474

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/VersionAndMapping.json
F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/MAP/map.jpg
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/OTHER/20240429_RTR0033980_Photo.pdf
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/OTHER/20241028_RTR0033980_Photo.pdf
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/PHOTO/Profile.jpg
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/PHOTO/TimePhoto_20240429_140649.jpg
z: F2_hyd_hk_11sw_a_r602_0_wt9_11SW-A-R602_0_20241029/PHOTO/TimePhoto_20241028_144628.jpg
File. 9 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033981\hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20240429\20250114115736_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028.zip
['VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/AUDIT/', 'F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028.json', 'F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/MAP/map.jpg', 'F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/OTHER/20241028_RTR0033981_Photo.pdf', 'F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/PHOTO/Profile.jpg', 'F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_150052.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/AUDIT/
z: F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028.json
Y2
F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028.json
202003200188963

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/VersionAndMapping.json
F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/MAP/map.jpg
z: F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/OTHER/20241028_RTR0033981_Photo.pdf
z: F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/PHOTO/Profile.jpg
z: F2_hyd_hk_11sw_a_r602_0_wt5_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_150052.jpg
File. 10 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033984\20250114110951_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.zip
['VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/AUDIT/', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.json', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/MAP/map.png', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033984_Photo.pdf', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/Profile.jpg', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_141345.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/AUDIT/
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.json
Y2
F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.json
202003200093175

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/VersionAndMapping.json
F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/MAP/map.png
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033984_Photo.pdf
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/Profile.jpg
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_141345.jpg
File. 11 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033984\20250114112930_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.zip
['VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/AUDIT/', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.json', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/VersionAndMapping.json', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/MAP/map.png', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033984_Photo.pdf', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/Profile.jpg', 'F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_141345.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/AUDIT/
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.json
Y2
F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028.json
202003200093175

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/VersionAndMapping.json
F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/VersionAndMapping.json
Y
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/MAP/map.png
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/OTHER/20241028_RTR0033984_Photo.pdf
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/Profile.jpg
z: F2_hyd_hk_11sw_a_r614_0_wt1_11SW-A-R614_0_20241028/PHOTO/TimePhoto_20241028_141345.jpg
File. 12 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0033994\20250114112721_RTR0033994_11SW-A-R602_0_20241028.zip
['VersionAndMapping.json', 'F2_RTR0033994_11SW-A-R602_0_20241028/AUDIT/', 'F2_RTR0033994_11SW-A-R602_0_20241028/RTR0033994_11SW-A-R602_0_20241028.json', 'F2_RTR0033994_11SW-A-R602_0_20241028/VersionAndMapping.json', 'F2_RTR0033994_11SW-A-R602_0_20241028/MAP/map.jpg', 'F2_RTR0033994_11SW-A-R602_0_20241028/OTHER/20241028_RTR0033994_Photo.pdf', 'F2_RTR0033994_11SW-A-R602_0_20241028/PHOTO/Profile.jpg', 'F2_RTR0033994_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_145743.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_RTR0033994_11SW-A-R602_0_20241028/AUDIT/
z: F2_RTR0033994_11SW-A-R602_0_20241028/RTR0033994_11SW-A-R602_0_20241028.json
Y2
F2_RTR0033994_11SW-A-R602_0_20241028/RTR0033994_11SW-A-R602_0_20241028.json
202003200188966

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_RTR0033994_11SW-A-R602_0_20241028/VersionAndMapping.json
F2_RTR0033994_11SW-A-R602_0_20241028/VersionAndMapping.json
Y
z: F2_RTR0033994_11SW-A-R602_0_20241028/MAP/map.jpg
z: F2_RTR0033994_11SW-A-R602_0_20241028/OTHER/20241028_RTR0033994_Photo.pdf
z: F2_RTR0033994_11SW-A-R602_0_20241028/PHOTO/Profile.jpg
z: F2_RTR0033994_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_145743.jpg
File. 13 / 13
L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (202410-202412)_F2\202410\20241028_W SWT\RTR0034003\RTR0034003_11SW-A-R602_0_20241028\20250114114757_RTR0034003_11SW-A-R602_0_20241028.zip
['VersionAndMapping.json', 'F2_RTR0034003_11SW-A-R602_0_20241028/AUDIT/', 'F2_RTR0034003_11SW-A-R602_0_20241028/RTR0034003_11SW-A-R602_0_20241028.json', 'F2_RTR0034003_11SW-A-R602_0_20241028/VersionAndMapping.json', 'F2_RTR0034003_11SW-A-R602_0_20241028/MAP/map.jpg', 'F2_RTR0034003_11SW-A-R602_0_20241028/OTHER/20241028_RTR0034003_Photo.pdf', 'F2_RTR0034003_11SW-A-R602_0_20241028/PHOTO/Profile.jpg', 'F2_RTR0034003_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20240429_122335.jpg', 'F2_RTR0034003_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_142855.jpg']
z: VersionAndMapping.json
VersionAndMapping.json
Y
z: F2_RTR0034003_11SW-A-R602_0_20241028/AUDIT/
z: F2_RTR0034003_11SW-A-R602_0_20241028/RTR0034003_11SW-A-R602_0_20241028.json
Y2
F2_RTR0034003_11SW-A-R602_0_20241028/RTR0034003_11SW-A-R602_0_20241028.json
202003200188972

C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:110: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
C:\Users\ckho\AppData\Local\Temp\ipykernel_2536\2792450771.py:145: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dall[i] = pd.concat([dall[i],d[i]])

z: F2_RTR0034003_11SW-A-R602_0_20241028/VersionAndMapping.json
F2_RTR0034003_11SW-A-R602_0_20241028/VersionAndMapping.json
Y
z: F2_RTR0034003_11SW-A-R602_0_20241028/MAP/map.jpg
z: F2_RTR0034003_11SW-A-R602_0_20241028/OTHER/20241028_RTR0034003_Photo.pdf
z: F2_RTR0034003_11SW-A-R602_0_20241028/PHOTO/Profile.jpg
z: F2_RTR0034003_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20240429_122335.jpg
z: F2_RTR0034003_11SW-A-R602_0_20241028/PHOTO/TimePhoto_20241028_142855.jpg

In [ ]:
#

triallist = ['VersionAndMapping.json', 'F2_RTR0004906_11SE-C-C39_0_20241126/AUDIT/', 'F2_RTR0004906_11SE-C-C39_0_20241126/OTHER/', 'F2_RTR0004906_11SE-C-C39_0_20241126/RTR0004906_11SE-C-C39_0_20241126.json', 'F2_RTR0004906_11SE-C-C39_0_20241126/VersionAndMapping.json', 'F2_RTR0004906_11SE-C-C39_0_20241126/MAP/RTR0004906 Tree Location.JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Concrete crack behind lean.JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Crown condition.JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Dead branch (1).JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Dead branch (2).JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Fungal fruiting bodies.JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Leaning.JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Overview.JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Root condition (1).JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Root condition (2).JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Root condition (3).JPG', 'F2_RTR0004906_11SE-C-C39_0_20241126/PHOTO/RTR0004906 - Trunk condition.JPG']

print('.json' in 'F2_RTR0004906_11SE-C-C39_0_20241126/RTR0004906_11SE-C-C39_0_20241126.json' and 'Version' not in 'F2_RTR0004906_11SE-C-C39_0_20241126/RTR0004906_11SE-C-C39_0_20241126.json')

True

In [ ]:
df_f2basic['form2.DEPTTreeID'].iloc[0]

'RTR0034003'

In [ ]:
data

{'form2': {'FormSubversion': '1.2',
  'ID': '94de1887-d843-4184-9317-0e0b7e24c624',
  'TreeGUID': 'fe40b278-d72a-44e3-8e51-abe363e3b56e',
  'ContractGUID': '36fe203a-543c-4d02-a68b-f592c337ce86',
  'FileRef': 'RTR0034003_11SW-AR602_20241028',
  'DepartmentGUID': 'b9604f7e-c99e-415b-8259-ffa2655783e4',
  'InspectionOfficerGUID': '2902076d-de6a-48ee-991d-e8aacdaf4e02',
  'DateOfInspection': '2024-10-28T14:11:27',
  'LastInspectionTime': '2024-04-29T00:00:00',
  'InspectionFrequency': '5ddc84b4-425b-40d3-995f-ecd8ae39bed3',
  'InspectionTimeSpent': '5e01fe1b-7915-494e-b1c3-9a8cd5876747',
  'LastExportDatetime': '2025-01-14T11:47:12.907',
  'LastImportDatetime': '2023-11-15T09:38:48.677',
  'LastUploadDatetime': None,
  'TreeSpecies': '5e10ffe7-7599-42e3-99f8-0479c0cda222',
  'TriageCategory': '2e25e614-714e-411b-9770-2fde7d96f153',
  'TreeHeight': 13.0,
  'CrownSpread': 9.0,
  'NoOfTrunk': 1,
  'DBHOfTreeTrunk1': 610.0,
  'DBHOfTreeTrunk2': None,
  'DBHOfTreeTrunk3': None,
  'DBHOfTreeTrunk4': None,
  'DBHOfTreeTrunk5': None,
  'AggregatedDBH': 610.0,
  'TreeRegisterNo': 'HYD/CW/00132',
  'OVTTreeRegisterNo': '',
  'FormRef': None,
  'MasterZoneGUID': '5f5bc8f5-633e-480a-92f1-8070584d65b7',
  'SubZoneGUID': 'e2b8fc60-9aff-4c38-9bfe-658442ff51d3',
  'EnglishLocation': 'LYTTELTON ROAD, Within 39 meters to the North-East of Lamppost No. 42773 that near THE UNIVERSITY OF HONG KONG',
  'ChineseLocation': '毗連巴丙頓道, 燈柱42773東北面40米內',
  'Category': '3d03b321-deda-4ba3-8296-669349d41131',
  'District': 'c6bfc889-d8f3-49c4-9602-f379a5b69697',
  'CoordinateX': 832576.774,
  'CoordinateY': 815980.265,
  'NearestLampPoleNumber': '42772',
  'SoilCrackOrCrackBehindLean': 'fc9fcf10-9754-404e-b55c-a4aaad23c1df',
  'SoilCrackOrCrackBehindLeanDescription': '',
  'RestrictionWithinDripline': 'b569a7b4-50b1-4b0d-bbba-753aa45cac35',
  'RestrictionWithinDriplineDescription': None,
  'SiteConditionsOtherObservations': '',
  'TreeVigor': '36fcd64d-5d4e-47c6-889a-411af63a7b79',
  'Lean': True,
  'AngleFromVertical': 45.0,
  'WindExposure': '62cf5984-8f30-4182-a35b-56bee33569b4',
  'WindExposureDescription': '',
  'WildlifeOrNestingSite': False,
  'WildlifeOrNestingSiteDescription': '',
  'CableOrBrace': False,
  'CableOrBraceDescription': '',
  'BrownRootRotDiseaseRecord': False,
  'BrownRootRotDiseaseRecordDescription': '',
  'TreeFailureRecord': False,
  'TreeFailureRecordDescription': '',
  'GeneralConditionsOtherObservations': "hyd_hk_11sw_a_r602_0_wt7, RTR0034003\r\nThe branches of the tree were broken during the impact of Typhoon Mangkhut. Following the typhoon, mitigation efforts were undertaken to address the damage and facilitate the tree's recovery. Sprouting branches emerged and gradually re-established, forming a new canopy.",
  'BranchConditionObservations': '',
  'CrownDensity': 'e3817575-172b-403f-a990-40a69ec03585',
  'CrownDensityDescription': None,
  'SparsityRatio': None,
  'ImbalancedCrown': True,
  'LiveCrownRatio': '9a216eda-0439-4346-be14-070593c4802e',
  'CrownLoad': 'd8819b2c-df1a-478e-b9ff-719b1e16c89a',
  'Foliage': '91bf8744-e064-4684-9b8e-131a2042c00f',
  'SpecifiedFoliageRatio': None,
  'LeaveSize': '16dace73-fd00-48fe-b8f3-82e95c5db951',
  'DiebackTwigsRatio': '45c520f6-7494-43ae-bd47-59b62a6c4285',
  'CorwnConditionsOtherObservations': 'No obvious signs of Phauda flammans was spotted during inspection.  ',
  'CrownUsePestDiseaseList': True,
  'CrownPestDisease': False,
  'CrownPestDiseaseGUID': None,
  'CrownDefoliationPercent': None,
  'Cavity': False,
  'Cavity1L': None,
  'Cavity2L': None,
  'Cavity3L': None,
  'Cavity4L': None,
  'Cavity1W': None,
  'Cavity2W': None,
  'Cavity3W': None,
  'Cavity4W': None,
  'Cavity1M': None,
  'Cavity2M': None,
  'Cavity3M': None,
  'Cavity4M': None,
  'Cavity1D': '',
  'Cavity2D': '',
  'Cavity3D': '',
  'Cavity4D': '',
  'Cavity1HeightAboveGround': None,
  'Cavity2HeightAboveGround': None,
  'Cavity3HeightAboveGround': None,
  'Cavity4HeightAboveGround': None,
  'TrunkConditionsOtherObservations': 'Noticeable lignified aerial root wrapped around the trunk',
  'RootConditionsOtherObservations': 'The root mat spreading was limited to the vertical wall. No obvious signs of BRRD were observed during the inspection.',
  'RCTreePart1': '499a500d-ae83-4b09-963b-786a11319ace',
  'RCTreePart1Size': 610,
  'RCTreePart1FallDistance': 13.0,
  'RCTreePart1ConditionofConcern': 'Wall tree, confined rooting space',
  'RCTreePart1Target1No': '1',
  'RCTreePart1Target1LikeihoodOfFailure': 'aa8c5446-40a4-42b1-a973-244592f9fb9f',
  'RCTreePart1Target1LikeihoodOfImpactingTarget': '26110147-a09a-4598-915b-4a156673c476',
  'RCTreePart1Target1LikeihoodOfFailureAndImpact': '9f20c621-b6ee-41bc-a93c-58c66d24f679',
  'RCTreePart1Target1Consequences': '636d0891-15aa-48da-b3fc-f8c389ae7476',
  'RCTreePart1Target1RiskRating': 'cb5c3c56-6ae0-4327-9d82-6d0a9c5afdf1',
  'RCTreePart1Target2No': '2',
  'RCTreePart1Target2LikeihoodOfFailure': 'aa8c5446-40a4-42b1-a973-244592f9fb9f',
  'RCTreePart1Target2LikeihoodOfImpactingTarget': '26110147-a09a-4598-915b-4a156673c476',
  'RCTreePart1Target2LikeihoodOfFailureAndImpact': '9f20c621-b6ee-41bc-a93c-58c66d24f679',
  'RCTreePart1Target2Consequences': 'cb4a4839-8961-42dd-b7e2-f2ae9c20af25',
  'RCTreePart1Target2RiskRating': 'cb5c3c56-6ae0-4327-9d82-6d0a9c5afdf1',
  'RCTreePart1Target3No': '3',
  'RCTreePart1Target3LikeihoodOfFailure': 'aa8c5446-40a4-42b1-a973-244592f9fb9f',
  'RCTreePart1Target3LikeihoodOfImpactingTarget': 'c6b688cb-10ed-45e8-a7ac-d1831f463dcd',
  'RCTreePart1Target3LikeihoodOfFailureAndImpact': 'c67fa76f-8a74-4ab1-8be2-22b26a1da8d3',
  'RCTreePart1Target3Consequences': 'cb4a4839-8961-42dd-b7e2-f2ae9c20af25',
  'RCTreePart1Target3RiskRating': 'b3a279e2-64fb-4da3-994f-4374728beee1',
  'RCTreePart2': None,
  'RCTreePart2Size': None,
  'RCTreePart2FallDistance': None,
  'RCTreePart2ConditionofConcern': '',
  'RCTreePart2Target1No': '',
  'RCTreePart2Target1LikeihoodOfFailure': None,
  'RCTreePart2Target1LikeihoodOfImpactingTarget': None,
  'RCTreePart2Target1LikeihoodOfFailureAndImpact': None,
  'RCTreePart2Target1Consequences': None,
  'RCTreePart2Target1RiskRating': None,
  'RCTreePart2Target2No': None,
  'RCTreePart2Target2LikeihoodOfFailure': None,
  'RCTreePart2Target2LikeihoodOfImpactingTarget': None,
  'RCTreePart2Target2LikeihoodOfFailureAndImpact': None,
  'RCTreePart2Target2Consequences': None,
  'RCTreePart2Target2RiskRating': None,
  'RCTreePart2Target3No': None,
  'RCTreePart2Target3LikeihoodOfFailure': None,
  'RCTreePart2Target3LikeihoodOfImpactingTarget': None,
  'RCTreePart2Target3LikeihoodOfFailureAndImpact': None,
  'RCTreePart2Target3Consequences': None,
  'RCTreePart2Target3RiskRating': None,
  'RCTreePart3': None,
  'RCTreePart3Size': None,
  'RCTreePart3FallDistance': None,
  'RCTreePart3ConditionofConcern': '',
  'RCTreePart3Target1No': '',
  'RCTreePart3Target1LikeihoodOfFailure': None,
  'RCTreePart3Target1LikeihoodOfImpactingTarget': None,
  'RCTreePart3Target1LikeihoodOfFailureAndImpact': None,
  'RCTreePart3Target1Consequences': None,
  'RCTreePart3Target1RiskRating': None,
  'RCTreePart3Target2No': None,
  'RCTreePart3Target2LikeihoodOfFailure': None,
  'RCTreePart3Target2LikeihoodOfImpactingTarget': None,
  'RCTreePart3Target2LikeihoodOfFailureAndImpact': None,
  'RCTreePart3Target2Consequences': None,
  'RCTreePart3Target2RiskRating': None,
  'RCTreePart3Target3No': None,
  'RCTreePart3Target3LikeihoodOfFailure': None,
  'RCTreePart3Target3LikeihoodOfImpactingTarget': None,
  'RCTreePart3Target3LikeihoodOfFailureAndImpact': None,
  'RCTreePart3Target3Consequences': None,
  'RCTreePart3Target3RiskRating': None,
  'MitigationMeasureRemark': "The tree was positioned on a retaining wall, with no signs of detachment observed. While part of the tree's root system extended to the slope toe, allowing access to additional resources, its contribution to the overall stability of the tree was considered minor. The foliage density, color, and size were normal, indicating a healthy state. During the inspection, no significant deterioration was noted in comparison to the previous Form 2 inspection. No sign of BRRD was noted during the inspection.",
  'OverallTreeRiskRating': '5b02c2bf-6068-4332-bfe8-48f1054a0357',
  'OverallResidualRisk': '5f322faf-ff09-43c4-b843-9f603463613c',
  'AdvancedAssessment': False,
  'AdvancedAssessmentYes': None,
  'AdvancedAssessmentDecription': None,
  'NextInspectionDate': '2025-04-30T00:00:00',
  'UserComment': None,
  'AuditorComment': None,
  'Status': 'f3de9b15-4ffe-438d-a4cf-6ede9a318fc8',
  'LastModifiedTime': '2025-01-14T11:47:12.49',
  'FileSizeByte': 11933606,
  'DEPTTreeID': 'RTR0034003',
  'ContractNo': '18/HY/2020',
  'InspectionOfficerFullName': 'TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy19.com.hk',
  'InspectionOfficerNameEnglish': 'HO CHAK KONG',
  'InspectionOfficerNameChinese': '何澤江',
  'InspectionOfficerPost': 'Tree Specialist',
  'MasterZoneNumber': '11SW-A/R602_0',
  'SubZoneNumber': '11SW-A/R602_0',
  'OfficerID': '1721',
  'MasterZoneID': '7020',
  'SubZoneID': '19288'},
 'attachment': [{'ID': 'baed6729-0c64-4bcb-883f-5975441fd253',
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'Type': 'f94caa2c-2dcf-4e02-8eb0-620c8c3de01d',
   'FileName': 'Profile.jpg',
   'FormType': None,
   'PhotoDate': None,
   'Description': '',
   'Remark': None,
   'OrderNo': None},
  {'ID': 'df3fc65d-a64b-485f-8c94-8a2900de289d',
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'Type': 'e1eb8ff0-4309-499f-a3f3-2623c26b1346',
   'FileName': 'TimePhoto_20241028_142855.jpg',
   'FormType': None,
   'PhotoDate': None,
   'Description': 'general view',
   'Remark': None,
   'OrderNo': 1},
  {'ID': 'd036ac03-5cc0-4c09-9085-c6104b6fa4ef',
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'Type': '275ef8e2-5aab-4868-83d2-2beea962bd86',
   'FileName': '20241028_RTR0034003_Photo.pdf',
   'FormType': None,
   'PhotoDate': None,
   'Description': 'report',
   'Remark': None,
   'OrderNo': 1},
  {'ID': '20c4e54c-1487-455d-b4d9-ecd6cfecf120',
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'Type': '3b5c5c46-994d-4f80-a2b9-0c508c0ba9ae',
   'FileName': 'map.jpg',
   'FormType': None,
   'PhotoDate': None,
   'Description': 'map',
   'Remark': None,
   'OrderNo': 1}],
 'tblLocationTypeList': [{'ID': '56919568-2db0-4aa1-835b-da3f2cdd5645',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'LocationType': 'a3954034-e4bd-4f64-97b1-527ba65dbaed',
   'Remark': '11SW-A/R602'}],
 'tblForm2TargetAssessmentList': [{'ID': '3a0e82d3-34a2-45f6-89e0-352e0974d10d',
   'TargetNo': 3,
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TargetDescriptionID': '8c100a0d-7ab0-4263-a466-4069cc1acb48',
   'TargetDescription': None,
   'TargetZone': '91ee31ad-a7cb-472a-ab84-0e3a4f675f5c',
   'OccupancyRate': '8b91f0b6-69f7-4bd4-b4da-001cbf767767',
   'RemoveTarget': False,
   'RestrictUsage': False},
  {'ID': '2124e59f-96e7-4a00-946c-4535be5548b5',
   'TargetNo': 1,
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TargetDescriptionID': '496df3da-e9dc-4fe0-bc7a-0cd0acf67136',
   'TargetDescription': None,
   'TargetZone': '91ee31ad-a7cb-472a-ab84-0e3a4f675f5c',
   'OccupancyRate': 'ab9c8207-c6c1-4cb4-a295-c84191692b47',
   'RemoveTarget': False,
   'RestrictUsage': False},
  {'ID': '27476e3c-1762-4b38-bbf8-7bffc97e02bb',
   'TargetNo': 2,
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TargetDescriptionID': '102dca59-c307-4dcc-b44e-d327df5ed91f',
   'TargetDescription': None,
   'TargetZone': '91ee31ad-a7cb-472a-ab84-0e3a4f675f5c',
   'OccupancyRate': 'ab9c8207-c6c1-4cb4-a295-c84191692b47',
   'RemoveTarget': False,
   'RestrictUsage': False},
  {'ID': '6ea7c7a3-48b7-49ea-9423-d5adaef19f53',
   'TargetNo': 4,
   'FormGUID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TargetDescriptionID': '9eb644d3-a155-46c1-b1f1-2a60f93d109e',
   'TargetDescription': None,
   'TargetZone': '91ee31ad-a7cb-472a-ab84-0e3a4f675f5c',
   'OccupancyRate': '61a0c1cf-1575-4cf1-a7dc-1aa51cf49d5b',
   'RemoveTarget': False,
   'RestrictUsage': False}],
 'tblForm2BranchConditionsList': [{'ID': 'bd8add94-f30f-4e78-8fbf-29d1115e6f8f',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'BranchConditionsType': 'd763ee9c-c0ba-4c33-add1-1e7031f55357',
   'Remark': None,
   'RemarkGUID': None},
  {'ID': '3a458adc-d7a7-4821-a4b0-44ebe3edfcab',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'BranchConditionsType': '9b36e166-7231-4ba9-8b78-7e1a3b057ecd',
   'Remark': None,
   'RemarkGUID': None},
  {'ID': '7af191bd-81c0-4aa0-a730-52365b8f0c36',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'BranchConditionsType': '93e489ae-96cb-4268-ba4a-ed695e81e920',
   'Remark': None,
   'RemarkGUID': None}],
 'tblForm2MitigationMeasuresList': [{'ID': '43b52ef0-29a2-4c41-8e85-47fbfa2e81e4',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TargetNo': 1,
   'TreePart': '499a500d-ae83-4b09-963b-786a11319ace',
   'MitigationMeasures': 'Others  其他Monitoring\r\n',
   'AnticipatedCompletionDate': '2025-04-30T00:00:00',
   'ResidualRisk': '5f322faf-ff09-43c4-b843-9f603463613c'}],
 'tblForm2PruningHistoryList': [{'ID': 'b8331de2-1ea4-4ad2-a356-7c998ef7ea62',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'PruningType': '516075d6-60a0-48a0-b145-d45c87ed5a07',
   'Remark': None},
  {'ID': 'acf47537-4cf7-40b9-92c7-7e547a5d57b1',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'PruningType': 'a6e570f1-4d08-4066-a44f-d6fe4d72f473',
   'Remark': None},
  {'ID': 'f9cf1962-edfa-49f7-b2fb-899b74319484',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'PruningType': '2ee70e7a-8dab-460b-998d-71e7bf33cdd7',
   'Remark': None},
  {'ID': '481b6c70-dfcd-4f57-9eb4-97b76dd91d73',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'PruningType': '345cdce8-54bc-448b-89a4-1e5db3e85c3d',
   'Remark': None}],
 'tblForm2RootConditionsList': [{'ID': '25d9872b-a0f2-4b92-a620-61df50aeb48c',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'RootConditionsType': '62ccab8c-750b-4b4a-8c9a-1385ce089a50',
   'Remark': None,
   'RemarkGUID': None},
  {'ID': 'ee742d0c-cff1-4965-b6a4-64d7037784cd',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'RootConditionsType': '4ae0e2e7-5d96-4d84-95d2-4adcc561247e',
   'Remark': 'A low volume of water-sprouts emerged on the root-stem transition zone',
   'RemarkGUID': None},
  {'ID': 'f26d39c2-d8d3-4b35-aeb8-98014428d289',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'RootConditionsType': '1f699248-328c-48b0-b6a2-16d9f2ab5061',
   'Remark': None,
   'RemarkGUID': None},
  {'ID': '34b438c8-4594-4cf6-9efa-a30d065b1fa7',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'RootConditionsType': '91f0ec74-d6db-4f32-87f3-fb34ca3d9718',
   'Remark': None,
   'RemarkGUID': None}],
 'tblForm2TrunkConditionList': [{'ID': '00fdc8e7-ed16-49ca-af5d-61a63330f522',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TrunkType': 'c84e6324-2a0b-4994-9236-7b8a6144364a',
   'Remark': None,
   'RemarkGUID': None},
  {'ID': 'c4dc6032-319f-4679-aab2-993b507bca5a',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TrunkType': 'b7de7a48-4041-4c65-8af1-bf07b9b2165b',
   'Remark': None,
   'RemarkGUID': None}],
 'tblForm2TreeOnTreeRegisterList': [{'ID': '3a2c4ae8-928c-42ca-b3b5-5f673f3badcc',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TreeRegisterType': '8837435c-6381-46ed-9acb-0d7e3b31129f',
   'Remark': None},
  {'ID': '97997cbc-dfef-4051-9ee6-733561c976d9',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TreeRegisterType': '1c9f5cec-641a-4217-9154-e4d501d0b192',
   'Remark': None},
  {'ID': 'ed62b87d-18ce-44b7-a971-c0d2f3b8d45a',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TreeRegisterType': '44ff3c1b-1e61-4a7b-a5cf-a09fd9290b3a',
   'Remark': None}],
 'tblForm2InspectionLimitationsList': [{'ID': '9e1e17ad-477c-49ed-b3cd-38c776a7f4db',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'LimitationType': '3257a6de-9d20-48a2-b6eb-f50667d615eb',
   'Remark': None}],
 'tblForm2DiebackTwigsTypeList': [{'ID': 'f14140f8-2749-45c9-8c47-fdf7aaf1430d',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'DiebackTwigsType': '6160cf27-3cb6-4f9f-a2ab-9ae701f103c5',
   'Remark': None}],
 'tblForm2LeanList': [{'ID': 'ab41ec4e-0e7a-4e5e-9c4d-1844b1f9ca4d',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'LeanType': '094d1e43-4ea2-478c-bd63-e1e02d30188a',
   'Remark': None},
  {'ID': '9f99f781-bf8f-4115-93eb-88ac08a2625a',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'LeanType': '4e54f182-bd8f-46b6-9292-f8752df7e896',
   'Remark': None}],
 'tblForm2SiteChangesList': [{'ID': 'd3865243-5d04-4e9c-a78b-b29c1a0d0482',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'SiteChangesType': '0295854f-424b-4706-a600-d5b075abd77d',
   'Remark': None}],
 'tblForm2SoilConditionsList': [{'ID': '0cadf8aa-89c3-4393-a676-68373e15433f',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'SoilConditionsType': '9e53ed1f-a46c-4700-90e5-94df4e921565',
   'Remark': None}],
 'tblForm2TopographyList': [{'ID': '34b4cd0b-3c6e-494c-90c3-3f4fc40c45dd',
   'FormID': '94de1887-d843-4184-9317-0e0b7e24c624',
   'TopographyType': '29befa86-1f2b-41e0-b793-9300a537aa67',
   'Remark': None}],
 'tblForm2AuditCommentList': [],
 'auditTabs': [],
 'TreeID': 'RTR0034003',
 'MasterZoneNo': '11SW-A/R602_0',
 'DateOfInspection': '2024-10-28T14:11:27'}

In [ ]:
df_f2.columns.to_list()

['attachment',
 'tblLocationTypeList',
 'tblForm2TargetAssessmentList',
 'tblForm2BranchConditionsList',
 'tblForm2MitigationMeasuresList',
 'tblForm2PruningHistoryList',
 'tblForm2RootConditionsList',
 'tblForm2TrunkConditionList',
 'tblForm2TreeOnTreeRegisterList',
 'tblForm2InspectionLimitationsList',
 'tblForm2DiebackTwigsTypeList',
 'tblForm2LeanList',
 'tblForm2SiteChangesList',
 'tblForm2SoilConditionsList',
 'tblForm2TopographyList',
 'tblForm2AuditCommentList',
 'auditTabs',
 'TreeID',
 'MasterZoneNo',
 'DateOfInspection',
 'form2.FormSubversion',
 'form2.ID',
 'form2.TreeGUID',
 'form2.ContractGUID',
 'form2.FileRef',
 'form2.DepartmentGUID',
 'form2.InspectionOfficerGUID',
 'form2.DateOfInspection',
 'form2.LastInspectionTime',
 'form2.InspectionFrequency',
 'form2.InspectionTimeSpent',
 'form2.LastExportDatetime',
 'form2.LastImportDatetime',
 'form2.LastUploadDatetime',
 'form2.TreeSpecies',
 'form2.TriageCategory',
 'form2.TreeHeight',
 'form2.CrownSpread',
 'form2.NoOfTrunk',
 'form2.DBHOfTreeTrunk1',
 'form2.DBHOfTreeTrunk2',
 'form2.DBHOfTreeTrunk3',
 'form2.DBHOfTreeTrunk4',
 'form2.DBHOfTreeTrunk5',
 'form2.AggregatedDBH',
 'form2.TreeRegisterNo',
 'form2.OVTTreeRegisterNo',
 'form2.FormRef',
 'form2.MasterZoneGUID',
 'form2.SubZoneGUID',
 'form2.EnglishLocation',
 'form2.ChineseLocation',
 'form2.Category',
 'form2.District',
 'form2.CoordinateX',
 'form2.CoordinateY',
 'form2.NearestLampPoleNumber',
 'form2.SoilCrackOrCrackBehindLean',
 'form2.SoilCrackOrCrackBehindLeanDescription',
 'form2.RestrictionWithinDripline',
 'form2.RestrictionWithinDriplineDescription',
 'form2.SiteConditionsOtherObservations',
 'form2.TreeVigor',
 'form2.Lean',
 'form2.AngleFromVertical',
 'form2.WindExposure',
 'form2.WindExposureDescription',
 'form2.WildlifeOrNestingSite',
 'form2.WildlifeOrNestingSiteDescription',
 'form2.CableOrBrace',
 'form2.CableOrBraceDescription',
 'form2.BrownRootRotDiseaseRecord',
 'form2.BrownRootRotDiseaseRecordDescription',
 'form2.TreeFailureRecord',
 'form2.TreeFailureRecordDescription',
 'form2.GeneralConditionsOtherObservations',
 'form2.BranchConditionObservations',
 'form2.CrownDensity',
 'form2.CrownDensityDescription',
 'form2.SparsityRatio',
 'form2.ImbalancedCrown',
 'form2.LiveCrownRatio',
 'form2.CrownLoad',
 'form2.Foliage',
 'form2.SpecifiedFoliageRatio',
 'form2.LeaveSize',
 'form2.DiebackTwigsRatio',
 'form2.CorwnConditionsOtherObservations',
 'form2.CrownUsePestDiseaseList',
 'form2.CrownPestDisease',
 'form2.CrownPestDiseaseGUID',
 'form2.CrownDefoliationPercent',
 'form2.Cavity',
 'form2.Cavity1L',
 'form2.Cavity2L',
 'form2.Cavity3L',
 'form2.Cavity4L',
 'form2.Cavity1W',
 'form2.Cavity2W',
 'form2.Cavity3W',
 'form2.Cavity4W',
 'form2.Cavity1M',
 'form2.Cavity2M',
 'form2.Cavity3M',
 'form2.Cavity4M',
 'form2.Cavity1D',
 'form2.Cavity2D',
 'form2.Cavity3D',
 'form2.Cavity4D',
 'form2.Cavity1HeightAboveGround',
 'form2.Cavity2HeightAboveGround',
 'form2.Cavity3HeightAboveGround',
 'form2.Cavity4HeightAboveGround',
 'form2.TrunkConditionsOtherObservations',
 'form2.RootConditionsOtherObservations',
 'form2.RCTreePart1',
 'form2.RCTreePart1Size',
 'form2.RCTreePart1FallDistance',
 'form2.RCTreePart1ConditionofConcern',
 'form2.RCTreePart1Target1No',
 'form2.RCTreePart1Target1LikeihoodOfFailure',
 'form2.RCTreePart1Target1LikeihoodOfImpactingTarget',
 'form2.RCTreePart1Target1LikeihoodOfFailureAndImpact',
 'form2.RCTreePart1Target1Consequences',
 'form2.RCTreePart1Target1RiskRating',
 'form2.RCTreePart1Target2No',
 'form2.RCTreePart1Target2LikeihoodOfFailure',
 'form2.RCTreePart1Target2LikeihoodOfImpactingTarget',
 'form2.RCTreePart1Target2LikeihoodOfFailureAndImpact',
 'form2.RCTreePart1Target2Consequences',
 'form2.RCTreePart1Target2RiskRating',
 'form2.RCTreePart1Target3No',
 'form2.RCTreePart1Target3LikeihoodOfFailure',
 'form2.RCTreePart1Target3LikeihoodOfImpactingTarget',
 'form2.RCTreePart1Target3LikeihoodOfFailureAndImpact',
 'form2.RCTreePart1Target3Consequences',
 'form2.RCTreePart1Target3RiskRating',
 'form2.RCTreePart2',
 'form2.RCTreePart2Size',
 'form2.RCTreePart2FallDistance',
 'form2.RCTreePart2ConditionofConcern',
 'form2.RCTreePart2Target1No',
 'form2.RCTreePart2Target1LikeihoodOfFailure',
 'form2.RCTreePart2Target1LikeihoodOfImpactingTarget',
 'form2.RCTreePart2Target1LikeihoodOfFailureAndImpact',
 'form2.RCTreePart2Target1Consequences',
 'form2.RCTreePart2Target1RiskRating',
 'form2.RCTreePart2Target2No',
 'form2.RCTreePart2Target2LikeihoodOfFailure',
 'form2.RCTreePart2Target2LikeihoodOfImpactingTarget',
 'form2.RCTreePart2Target2LikeihoodOfFailureAndImpact',
 'form2.RCTreePart2Target2Consequences',
 'form2.RCTreePart2Target2RiskRating',
 'form2.RCTreePart2Target3No',
 'form2.RCTreePart2Target3LikeihoodOfFailure',
 'form2.RCTreePart2Target3LikeihoodOfImpactingTarget',
 'form2.RCTreePart2Target3LikeihoodOfFailureAndImpact',
 'form2.RCTreePart2Target3Consequences',
 'form2.RCTreePart2Target3RiskRating',
 'form2.RCTreePart3',
 'form2.RCTreePart3Size',
 'form2.RCTreePart3FallDistance',
 'form2.RCTreePart3ConditionofConcern',
 'form2.RCTreePart3Target1No',
 'form2.RCTreePart3Target1LikeihoodOfFailure',
 'form2.RCTreePart3Target1LikeihoodOfImpactingTarget',
 'form2.RCTreePart3Target1LikeihoodOfFailureAndImpact',
 'form2.RCTreePart3Target1Consequences',
 'form2.RCTreePart3Target1RiskRating',
 'form2.RCTreePart3Target2No',
 'form2.RCTreePart3Target2LikeihoodOfFailure',
 'form2.RCTreePart3Target2LikeihoodOfImpactingTarget',
 'form2.RCTreePart3Target2LikeihoodOfFailureAndImpact',
 'form2.RCTreePart3Target2Consequences',
 'form2.RCTreePart3Target2RiskRating',
 'form2.RCTreePart3Target3No',
 'form2.RCTreePart3Target3LikeihoodOfFailure',
 'form2.RCTreePart3Target3LikeihoodOfImpactingTarget',
 'form2.RCTreePart3Target3LikeihoodOfFailureAndImpact',
 'form2.RCTreePart3Target3Consequences',
 'form2.RCTreePart3Target3RiskRating',
 'form2.MitigationMeasureRemark',
 'form2.OverallTreeRiskRating',
 'form2.OverallResidualRisk',
 'form2.AdvancedAssessment',
 'form2.AdvancedAssessmentYes',
 'form2.AdvancedAssessmentDecription',
 'form2.NextInspectionDate',
 'form2.UserComment',
 'form2.AuditorComment',
 'form2.Status',
 'form2.LastModifiedTime',
 'form2.FileSizeByte',
 'form2.DEPTTreeID',
 'form2.ContractNo',
 'form2.InspectionOfficerFullName',
 'form2.InspectionOfficerNameEnglish',
 'form2.InspectionOfficerNameChinese',
 'form2.InspectionOfficerPost',
 'form2.MasterZoneNumber',
 'form2.SubZoneNumber',
 'form2.OfficerID',
 'form2.MasterZoneID',
 'form2.SubZoneID']

In [ ]:
df_dbtreeList= pd.json_normalize(datameta, record_path = ['treeList'])
df_dbtreeList

,ID,TreeID,DEPTTreeID,SpeciesCode,SpeciesTypeCode,MasterZoneID,SubZoneID,TriageColourCode,TriageColourTypeCode,X,Y,isNewTree
0,a2737c38-fb6f-46cf-867e-0000b525f6d2,202003200081225,RTR0002772,514,TreeSpecies,6383,18651,None,None,837747.133,813843.561,False
1,61f7fd85-225a-4227-a6bc-00026d410def,202003200040625,RTR0020104,236,TreeSpecies,9386,21653,None,None,838568.832,810496.441,False
2,fd3b4478-e880-4fa0-82e9-000329bb800b,202003200087798,RTR0013299,169,TreeSpecies,6693,18961,None,None,841592.097,813138.167,False
3,34d79974-bcce-40ce-99d2-0004d45bd9f4,202003200088745,RTR0094282,473,TreeSpecies,9774,22041,None,None,835241.977,811277.595,False
4,444425f0-1041-4c97-bfcf-0005309a7211,202003200053564,RTR0097323,138,TreeSpecies,7197,19465,None,None,834158.013,815595.844,False
...,...,...,...,...,...,...,...,...,...,...,...,...
55862,7ced2e0c-1c84-4f45-a38b-fffe5520ebd5,202003200004177,RTR0019841,335,TreeSpecies,9460,21727,None,None,841102.751,810661.118,False
55863,d109f5db-1eff-48a4-a6b0-fffe90d9feb1,202003200010662,RTR0020449,111,TreeSpecies,9427,21694,None,None,841076.869,810863.337,False
55864,3690638f-6e80-49a3-8094-fffefa36054f,202003200191936,RTR0035265,333,TreeSpecies,7600,19867,None,None,831524.012,813922.678,False
55865,eea985d6-b11b-4b91-b5f5-ffff4e8937a7,202103200000015,ETR0630012,229,TreeSpecies,29672,49723,None,None,833739.073,815473.083,False
55866,84b1c8bd-2975-41bd-b76c-fffffb2d674e,202003200092697,RTR0093388,333,TreeSpecies,9758,22025,None,None,835279.051,811180.511,False

In [ ]:
zipfile

In [ ]:
dferrorlist = pd.DataFrame(errlist)
dferrorlist.to_excel(xlErrPath)

In [ ]:
errlist

[]

## cont

In [ ]:
dall.keys()

dict_keys(['attachment', 'tblLocationTypeList', 'tblForm2TargetAssessmentList', 'tblForm2BranchConditionsList', 'tblForm2MitigationMeasuresList', 'tblForm2PruningHistoryList', 'tblForm2RootConditionsList', 'tblForm2TrunkConditionList', 'tblForm2TreeOnTreeRegisterList', 'tblForm2InspectionLimitationsList', 'tblForm2DiebackTwigsTypeList', 'tblForm2LeanList', 'tblForm2SiteChangesList', 'tblForm2SoilConditionsList', 'tblForm2TopographyList', 'tblForm2AuditCommentList', 'auditTabs'])

In [ ]:
#dall['tblForm2MitigationMeasuresList']

## 除中文字

In [ ]:
df_f2basicAll.columns.to_list()

['MasterZoneNo',
 'DateOfInspection',
 'form2.FormSubversion',
 'form2.ID',
 'form2.TreeGUID',
 'form2.ContractGUID',
 'form2.FileRef',
 'form2.DepartmentGUID',
 'form2.InspectionOfficerGUID',
 'form2.DateOfInspection',
 'form2.LastInspectionTime',
 'form2.InspectionFrequency',
 'form2.InspectionTimeSpent',
 'form2.LastExportDatetime',
 'form2.LastImportDatetime',
 'form2.LastUploadDatetime',
 'form2.TreeSpecies',
 'form2.TriageCategory',
 'form2.TreeHeight',
 'form2.CrownSpread',
 'form2.NoOfTrunk',
 'form2.DBHOfTreeTrunk1',
 'form2.DBHOfTreeTrunk2',
 'form2.DBHOfTreeTrunk3',
 'form2.DBHOfTreeTrunk4',
 'form2.DBHOfTreeTrunk5',
 'form2.AggregatedDBH',
 'form2.TreeRegisterNo',
 'form2.OVTTreeRegisterNo',
 'form2.FormRef',
 'form2.MasterZoneGUID',
 'form2.SubZoneGUID',
 'form2.EnglishLocation',
 'form2.ChineseLocation',
 'form2.Category',
 'form2.District',
 'form2.CoordinateX',
 'form2.CoordinateY',
 'form2.NearestLampPoleNumber',
 'form2.SoilCrackOrCrackBehindLean',
 'form2.SoilCrackOrCrackBehindLeanDescription',
 'form2.RestrictionWithinDripline',
 'form2.RestrictionWithinDriplineDescription',
 'form2.SiteConditionsOtherObservations',
 'form2.TreeVigor',
 'form2.Lean',
 'form2.AngleFromVertical',
 'form2.WindExposure',
 'form2.WindExposureDescription',
 'form2.WildlifeOrNestingSite',
 'form2.WildlifeOrNestingSiteDescription',
 'form2.CableOrBrace',
 'form2.CableOrBraceDescription',
 'form2.BrownRootRotDiseaseRecord',
 'form2.BrownRootRotDiseaseRecordDescription',
 'form2.TreeFailureRecord',
 'form2.TreeFailureRecordDescription',
 'form2.GeneralConditionsOtherObservations',
 'form2.BranchConditionObservations',
 'form2.CrownDensity',
 'form2.CrownDensityDescription',
 'form2.SparsityRatio',
 'form2.ImbalancedCrown',
 'form2.LiveCrownRatio',
 'form2.CrownLoad',
 'form2.Foliage',
 'form2.SpecifiedFoliageRatio',
 'form2.LeaveSize',
 'form2.DiebackTwigsRatio',
 'form2.CorwnConditionsOtherObservations',
 'form2.CrownUsePestDiseaseList',
 'form2.CrownPestDisease',
 'form2.CrownPestDiseaseGUID',
 'form2.CrownDefoliationPercent',
 'form2.Cavity',
 'form2.Cavity1L',
 'form2.Cavity2L',
 'form2.Cavity3L',
 'form2.Cavity4L',
 'form2.Cavity1W',
 'form2.Cavity2W',
 'form2.Cavity3W',
 'form2.Cavity4W',
 'form2.Cavity1M',
 'form2.Cavity2M',
 'form2.Cavity3M',
 'form2.Cavity4M',
 'form2.Cavity1D',
 'form2.Cavity2D',
 'form2.Cavity3D',
 'form2.Cavity4D',
 'form2.Cavity1HeightAboveGround',
 'form2.Cavity2HeightAboveGround',
 'form2.Cavity3HeightAboveGround',
 'form2.Cavity4HeightAboveGround',
 'form2.TrunkConditionsOtherObservations',
 'form2.RootConditionsOtherObservations',
 'form2.RCTreePart1',
 'form2.RCTreePart1Size',
 'form2.RCTreePart1FallDistance',
 'form2.RCTreePart1ConditionofConcern',
 'form2.RCTreePart1Target1No',
 'form2.RCTreePart1Target1LikeihoodOfFailure',
 'form2.RCTreePart1Target1LikeihoodOfImpactingTarget',
 'form2.RCTreePart1Target1LikeihoodOfFailureAndImpact',
 'form2.RCTreePart1Target1Consequences',
 'form2.RCTreePart1Target1RiskRating',
 'form2.RCTreePart1Target2No',
 'form2.RCTreePart1Target2LikeihoodOfFailure',
 'form2.RCTreePart1Target2LikeihoodOfImpactingTarget',
 'form2.RCTreePart1Target2LikeihoodOfFailureAndImpact',
 'form2.RCTreePart1Target2Consequences',
 'form2.RCTreePart1Target2RiskRating',
 'form2.RCTreePart1Target3No',
 'form2.RCTreePart1Target3LikeihoodOfFailure',
 'form2.RCTreePart1Target3LikeihoodOfImpactingTarget',
 'form2.RCTreePart1Target3LikeihoodOfFailureAndImpact',
 'form2.RCTreePart1Target3Consequences',
 'form2.RCTreePart1Target3RiskRating',
 'form2.RCTreePart2',
 'form2.RCTreePart2Size',
 'form2.RCTreePart2FallDistance',
 'form2.RCTreePart2ConditionofConcern',
 'form2.RCTreePart2Target1No',
 'form2.RCTreePart2Target1LikeihoodOfFailure',
 'form2.RCTreePart2Target1LikeihoodOfImpactingTarget',
 'form2.RCTreePart2Target1LikeihoodOfFailureAndImpact',
 'form2.RCTreePart2Target1Consequences',
 'form2.RCTreePart2Target1RiskRating',
 'form2.RCTreePart2Target2No',
 'form2.RCTreePart2Target2LikeihoodOfFailure',
 'form2.RCTreePart2Target2LikeihoodOfImpactingTarget',
 'form2.RCTreePart2Target2LikeihoodOfFailureAndImpact',
 'form2.RCTreePart2Target2Consequences',
 'form2.RCTreePart2Target2RiskRating',
 'form2.RCTreePart2Target3No',
 'form2.RCTreePart2Target3LikeihoodOfFailure',
 'form2.RCTreePart2Target3LikeihoodOfImpactingTarget',
 'form2.RCTreePart2Target3LikeihoodOfFailureAndImpact',
 'form2.RCTreePart2Target3Consequences',
 'form2.RCTreePart2Target3RiskRating',
 'form2.RCTreePart3',
 'form2.RCTreePart3Size',
 'form2.RCTreePart3FallDistance',
 'form2.RCTreePart3ConditionofConcern',
 'form2.RCTreePart3Target1No',
 'form2.RCTreePart3Target1LikeihoodOfFailure',
 'form2.RCTreePart3Target1LikeihoodOfImpactingTarget',
 'form2.RCTreePart3Target1LikeihoodOfFailureAndImpact',
 'form2.RCTreePart3Target1Consequences',
 'form2.RCTreePart3Target1RiskRating',
 'form2.RCTreePart3Target2No',
 'form2.RCTreePart3Target2LikeihoodOfFailure',
 'form2.RCTreePart3Target2LikeihoodOfImpactingTarget',
 'form2.RCTreePart3Target2LikeihoodOfFailureAndImpact',
 'form2.RCTreePart3Target2Consequences',
 'form2.RCTreePart3Target2RiskRating',
 'form2.RCTreePart3Target3No',
 'form2.RCTreePart3Target3LikeihoodOfFailure',
 'form2.RCTreePart3Target3LikeihoodOfImpactingTarget',
 'form2.RCTreePart3Target3LikeihoodOfFailureAndImpact',
 'form2.RCTreePart3Target3Consequences',
 'form2.RCTreePart3Target3RiskRating',
 'form2.MitigationMeasureRemark',
 'form2.OverallTreeRiskRating',
 'form2.OverallResidualRisk',
 'form2.AdvancedAssessment',
 'form2.AdvancedAssessmentYes',
 'form2.AdvancedAssessmentDecription',
 'form2.NextInspectionDate',
 'form2.UserComment',
 'form2.AuditorComment',
 'form2.Status',
 'form2.LastModifiedTime',
 'form2.FileSizeByte',
 'form2.DEPTTreeID',
 'form2.ContractNo',
 'form2.InspectionOfficerFullName',
 'form2.InspectionOfficerNameEnglish',
 'form2.InspectionOfficerNameChinese',
 'form2.InspectionOfficerPost',
 'form2.MasterZoneNumber',
 'form2.SubZoneNumber',
 'form2.OfficerID',
 'form2.MasterZoneID',
 'form2.SubZoneID']

In [ ]:
df_f2basicAll['form2.DepartmentGUID'] #=> form2.DepartmentGUID relate to treeList [ID]

0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
0    b9604f7e-c99e-415b-8259-ffa2655783e4
Name: form2.DepartmentGUID, dtype: object

In [ ]:
df_f2basicSummaryAll = df_f2basicAll[['form2.DEPTTreeID',
 'MasterZoneNo',
 'DateOfInspection',
 'form2.FormSubversion',
 'form2.FileRef',
 'form2.DateOfInspection',
 'form2.LastInspectionTime',
 'form2.InspectionFrequency',
 'form2.TreeSpecies',
 'form2.TriageCategory',
 'form2.TreeHeight',
 'form2.CrownSpread',
 'form2.AggregatedDBH',
 'form2.TreeVigor',
 'form2.AngleFromVertical',
 'form2.OverallTreeRiskRating',
 'form2.OverallResidualRisk',
 'form2.CoordinateX',
 'form2.CoordinateY',
 'form2.SoilCrackOrCrackBehindLean',
 'form2.RestrictionWithinDripline',
 'form2.NextInspectionDate',
 'form2.InspectionOfficerNameEnglish'
]]

df_mitigationAll = dall['tblForm2MitigationMeasuresList'].iloc[:,2:]       #自訂義勾其他columns
df_TreeRegAll = dall['tblForm2TreeOnTreeRegisterList'].iloc[:,2:]

df_f2SummaryResult = df_f2basicSummaryAll.merge(df_mitigationAll, left_on='form2.DEPTTreeID', right_on='TreeID')
df_f2SummaryResult = df_f2SummaryResult.merge(df_TreeRegAll, left_on='TreeID', right_on='TreeID')

# remove ENTER tab
df_f2SummaryResult.MitigationMeasures = df_f2SummaryResult.MitigationMeasures.str.replace('\r\n', ';').str[:-1]
df_f2SummaryResult = df_f2SummaryResult.iloc[:,1:]
df_f2SummaryResult

,MasterZoneNo,DateOfInspection,form2.FormSubversion,form2.FileRef,form2.DateOfInspection,form2.LastInspectionTime,form2.InspectionFrequency,form2.TreeSpecies,form2.TriageCategory,form2.TreeHeight,...,ResidualRisk,TreeID,TMCPTreeID_x,OverallComment_x,fldPath_x,TreeRegisterType,Remark,TMCPTreeID_y,OverallComment_y,fldPath_y
0,11SW-A/R577_0,2024-10-28T15:10:27,1.2,ETR0610143_11SW-AR577_20241028,2024-10-28T15:10:27,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,4.0,...,Moderate,ETR0610143,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoST,None,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
1,11SW-A/R577_0,2024-10-28T15:10:27,1.2,ETR0610143_11SW-AR577_20241028,2024-10-28T15:10:27,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,4.0,...,Moderate,ETR0610143,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoCS,None,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
2,11SW-A/R577_0,2024-10-28T15:10:27,1.2,ETR0610143_11SW-AR577_20241028,2024-10-28T15:10:27,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,4.0,...,Moderate,ETR0610143,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoST,None,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
3,11SW-A/R577_0,2024-10-28T15:10:27,1.2,ETR0610143_11SW-AR577_20241028,2024-10-28T15:10:27,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,4.0,...,Moderate,ETR0610143,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoCS,None,202403200001163,The tree is situated on a retaining wall besid...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
4,11SW-A/R577_0,2024-10-28T15:00:17,1.2,ETR0610144_11SW-AR577_20241028,2024-10-28T15:00:17,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,5.0,...,Moderate,ETR0610144,202403200001161,\nThe tree is situated on a retaining wall bes...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoCS,None,202403200001161,\nThe tree is situated on a retaining wall bes...,L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,11SW-A/R602_0,2024-10-28T14:45:16,1.2,RTR0033994_11SW-AR602_20241028,2024-10-28T14:45:16,2023-10-20T00:00:00,6 months,Ficus microcarpa,Red,10.0,...,Low,RTR0033994,202003200188966,"The tree is situated on a retaining wall, with...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoMT,None,202003200188966,"The tree is situated on a retaining wall, with...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
57,11SW-A/R602_0,2024-10-28T14:45:16,1.2,RTR0033994_11SW-AR602_20241028,2024-10-28T14:45:16,2023-10-20T00:00:00,6 months,Ficus microcarpa,Red,10.0,...,Low,RTR0033994,202003200188966,"The tree is situated on a retaining wall, with...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoST,None,202003200188966,"The tree is situated on a retaining wall, with...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
58,11SW-A/R602_0,2024-10-28T14:11:27,1.2,RTR0034003_11SW-AR602_20241028,2024-10-28T14:11:27,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,13.0,...,Moderate,RTR0034003,202003200188972,"The tree was positioned on a retaining wall, w...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoMT,None,202003200188972,"The tree was positioned on a retaining wall, w...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
59,11SW-A/R602_0,2024-10-28T14:11:27,1.2,RTR0034003_11SW-AR602_20241028,2024-10-28T14:11:27,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,13.0,...,Moderate,RTR0034003,202003200188972,"The tree was positioned on a retaining wall, w...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoST,None,202003200188972,"The tree was positioned on a retaining wall, w...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...
60,11SW-A/R602_0,2024-10-28T14:11:27,1.2,RTR0034003_11SW-AR602_20241028,2024-10-28T14:11:27,2024-04-29T00:00:00,6 months,Ficus microcarpa,Red,13.0,...,Moderate,RTR0034003,202003200188972,"The tree was positioned on a retaining wall, w...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...,cbxForm2_TreeInfoCS,None,202003200188972,"The tree was positioned on a retaining wall, w...",L:\LU\Staff\Ricky\TS\01-OVT+SWT\15-Batch 15 (2...

In [ ]:
#除中文字
# https://stackoverflow.com/questions/2718196/find-all-chinese-text-in-a-string-using-python-and-regex

df_f2SummaryResult['MitigationMeasures'] = df_f2SummaryResult['MitigationMeasures'].astype(str)

import re
sublist = []
for index, row in df_f2SummaryResult.iterrows():

    cell = []
    for n in re.findall(r'[^\u4e00-\u9fff]+', row['MitigationMeasures']):

        cell.append(n)
        #print(cell)

    #print(row['c1'], row['c2'])
    sublist.append(cell)

print(sublist)

[['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring;Crown reduction  ', ';Crown thinning  '], ['Others  ', 'Monitoring;Crown reduction  ', ';Crown thinning  '], ['Others  ', 'Monitoring;Crown thinning  ', ';Crown reduction  '], ['Others  ', 'Monitoring;Crown thinning  ', ';Crown reduction  '], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Crown thinning  ', ';Crown reduction  '], ['Crown thinning  ', ';Crown reduction  '], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Crown cleaning  '], ['Crown cleaning  '], ['Crown cleaning  '], ['Others  ', 'monitoring'], ['Others  ', 'monitoring'], ['Others  ', 'monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring'], ['Others  ', 'Monitoring']]

In [ ]:
df_f2SummaryResult['MitigationMeasures_Eng'] = sublist
df_f2SummaryResult['MitigationMeasures_Eng'] = df_f2SummaryResult['MitigationMeasures_Eng'].apply(lambda x: ', '.join(map(str, x)))
df_f2SummaryResult['MitigationMeasures_Eng'] = df_f2SummaryResult['MitigationMeasures_Eng'].str.replace("Others  ,", "Others:")
df_f2SummaryResult

df_f2SummaryResult.to_excel(xlExportPath)

## staff id

In [ ]:
df_summarymeta = pd.json_normalize(datameta)
df_summarymeta

,masterValueList,contractList,departmentList,inspectionOfficerList,masterZoneList,subZoneList,treeList,csvVersion.GUID,csvVersion.WINCLIENT_DATE,csvVersion.EXPORT_DATETIME
0,[{'ID': '9ec10ef5-fef8-40db-bffc-000567b0e871'...,[{'ID': 'ba803d1d-f36b-4b60-ac63-03baa1967e01'...,[{'ID': '2edf1c55-e512-4600-879a-115d4ce1ef76'...,[{'ID': '8ae7020b-27b4-4d75-a3aa-05b713c442e5'...,[{'ID': '47fd98d1-87d4-40f9-b7dc-00068aa47b3a'...,[{'ID': '998b009a-467d-4f36-bfe5-000a04cce7a4'...,[{'ID': 'a2737c38-fb6f-46cf-867e-0000b525f6d2'...,42c909ce-e472-43af-a32c-93d8c3b429bc,2025-01-14T10:53:00,2025-01-14T11:34:00

In [ ]:
df_staffGUID = pd.json_normalize(datameta, record_path = ['inspectionOfficerList'])

df_staffGUID['InspectionOfficerID'] = df_staffGUID['InspectionOfficerID'].astype(str)
df_staffGUID.head()

                                     ID InspectionOfficerID
0  8ae7020b-27b4-4d75-a3aa-05b713c442e5                4119
1  33977358-ebcd-4c81-81b8-09888a35b2ed                4185
2  e8d17e08-0699-46d7-8422-2012b2864edf                3535
3  c417ddea-0d6b-499f-ace6-230224e06458                4049
4  a699d798-ae6e-4548-8c4d-2967638c7c5c                1352

In [ ]:
dCsv['TBL_INSPECTOR.csv']['INSP_OF_OFFICER_ID'] = dCsv['TBL_INSPECTOR.csv']['INSP_OF_OFFICER_ID'].astype(str)
dCsv['TBL_INSPECTOR.csv'].head()

,ID,CSV_CODE,INSP_OF_OFFICER_ID,INSP_OF_NAME_ENG,INSP_OF_NAME_CHI,INSP_OF_POST,INSP_OF_UNIQUE_ID,LU_DEPT_CODE,INSP_OF_EMAIL_ADDRESS,INSP_OF_CONTRACT_ID,VERSION_DATETIME,EXPORT_DATETIME,DISPLAY,SORT
0,4043,NaN,4043,CHAN CHUEN KIU,陳泉橋,Assistant Arborist,AA14,32,chanchuenkiu@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,1
1,839,NaN,839,"CHAN HO MAN, TIMOTHY",陳灝文,Assistant Arborist,AA07,32,hmchan@sy12hy19.com.hk,1794,12/06/2024 15:57,01/14/2025 11:34,Y,2
2,4044,NaN,4044,CHAN KING HEI,陳景曦,Arborist,CHANKINGHEI,32,davy.chan@baguio.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,3
3,4119,NaN,4119,CHAN Shuk Han,NaN,Arborist,CHANSHUKHAN,32,NaN,1794,12/06/2024 15:58,01/14/2025 11:34,Y,4
4,840,NaN,840,"CHAN SIU LUNG, TANGO",陳小龍,Assistant Arborist,AA08,32,slchan@sy12hy19.com.hk,1794,12/06/2024 15:57,01/14/2025 11:34,Y,5

In [ ]:
df_staff = pd.merge(df_staffGUID, dCsv['TBL_INSPECTOR.csv'], left_on='InspectionOfficerID', right_on='INSP_OF_OFFICER_ID')
df_staff

,ID_x,InspectionOfficerID,ID_y,CSV_CODE,INSP_OF_OFFICER_ID,INSP_OF_NAME_ENG,INSP_OF_NAME_CHI,INSP_OF_POST,INSP_OF_UNIQUE_ID,LU_DEPT_CODE,INSP_OF_EMAIL_ADDRESS,INSP_OF_CONTRACT_ID,VERSION_DATETIME,EXPORT_DATETIME,DISPLAY,SORT
0,8ae7020b-27b4-4d75-a3aa-05b713c442e5,4119,4119,NaN,4119,CHAN Shuk Han,NaN,Arborist,CHANSHUKHAN,32,NaN,1794,12/06/2024 15:58,01/14/2025 11:34,Y,4
1,33977358-ebcd-4c81-81b8-09888a35b2ed,4185,4185,NaN,4185,Chu Ching Ki,NaN,Arborist,CHUCHINGKI,32,NaN,1794,01/06/2025 12:03,01/14/2025 11:34,Y,9
2,c417ddea-0d6b-499f-ace6-230224e06458,4049,4049,NaN,4049,FUNG Ho Tsang,馮浩錚,Arborist,FUNGHOTSANG,32,hftsoi@winghoyuen.com,1794,12/06/2024 15:59,01/14/2025 11:34,Y,11
3,fce16a15-b137-40e0-986d-2b240d4c01b8,4048,4048,NaN,4048,YUEN PIK YEE,袁碧兒,Arborist,YUENPIKYEE,32,lynn.yuen@baguio.com.hk,1794,12/06/2024 15:59,01/14/2025 11:34,Y,32
4,e116448b-9d88-45ee-8401-4d549d955ba0,4046,4046,NaN,4046,LUK KA CHUN,陸加俊,Arborist,LUKKACHUN,32,fung.cheng@baguio.com.hk,1794,12/06/2024 15:59,01/14/2025 11:34,Y,21
5,59303722-6cf1-4fa4-83e1-53387bbbe452,1722,1722,NaN,1722,"WU SIN CHING, CATHERINE",胡倩菁,Arborist,AR08,32,scwu@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,27
6,694061e7-645a-4f8a-9b53-5a6b118fe400,4121,4121,NaN,4121,WAN Wut Hang,NaN,Arborist,WANWUTHANG,32,NaN,1794,12/06/2024 15:59,01/14/2025 11:34,Y,24
7,e5366768-1631-47f1-977c-62792d619475,4149,4149,NaN,4149,Cheung Wang,NaN,Arborist,CHEUNGWANG,32,NaN,1794,12/17/2024 11:53,01/14/2025 11:34,Y,8
8,df75d7aa-8d7d-4855-8746-64ba4a1b00b8,532,532,NaN,532,"LAW CHI KA, CHRIS",羅志嘉,Tree Specialist,TS02,32,cklaw@sy12hy19.com.hk,1794,12/06/2024 15:59,01/14/2025 11:34,Y,18
9,172bc8bb-43dc-4a21-8075-68a02e6c1532,839,839,NaN,839,"CHAN HO MAN, TIMOTHY",陳灝文,Assistant Arborist,AA07,32,hmchan@sy12hy19.com.hk,1794,12/06/2024 15:57,01/14/2025 11:34,Y,2
10,3517304c-87d6-4864-ac6d-70e82beac579,535,535,NaN,535,"YEUNG MO YIN, DEREK",楊武研,Arborist,AR03,32,myyeun@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,29
11,1cd7ef4d-ef1b-4ab7-b195-7278bf0cf5f2,552,552,NaN,552,HO CHUN YIP,何駿業,Arborist,AR06,32,cyho@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,14
12,6afb0b58-3ee8-4b63-aed6-72a43a2d9516,548,548,NaN,548,"LAI SIK YIU, YOYO",黎軾瑤,Assistant Arborist,AA01,32,sylai@sy12hy19.com.hk,1794,12/06/2024 15:56,01/14/2025 11:34,Y,17
13,8cb2dcb0-3cac-4212-968e-7793ec00c6fd,4184,4184,NaN,4184,Chu Wing Shuen,NaN,Arborist,CHUWINGSHEUN,32,NaN,1794,01/06/2025 12:03,01/14/2025 11:34,Y,10
14,d4893249-04c0-4c8f-9537-78086b0a23fc,4122,4122,NaN,4122,WONG Chun Cheung,NaN,Arborist,WONGCHUNCHEUNG,32,NaN,1794,12/06/2024 15:59,01/14/2025 11:34,Y,25
15,0900537e-44f0-4442-95f3-7e61bacd24a6,4183,4183,NaN,4183,HUI WING LAP,NaN,Arborist,HUIWINGLAP,32,NaN,1794,01/06/2025 12:03,01/14/2025 11:34,Y,16
16,a8dce11f-27b0-4cee-8254-7f39a0feab6e,840,840,NaN,840,"CHAN SIU LUNG, TANGO",陳小龍,Assistant Arborist,AA08,32,slchan@sy12hy19.com.hk,1794,12/06/2024 15:57,01/14/2025 11:34,Y,5
17,6e962e8d-84a4-4bb0-91b5-89c40f71ae96,4044,4044,NaN,4044,CHAN KING HEI,陳景曦,Arborist,CHANKINGHEI,32,davy.chan@baguio.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,3
18,291cbee9-6269-4625-8eea-958361213442,1350,1350,NaN,1350,HO KWAN WING,何坤穎,Assistant Arborist,AA09,32,kwho@sy12hy19.com.hk,1794,12/06/2024 15:57,01/14/2025 11:34,Y,15
19,113b5052-3a24-4c8a-a767-97529214bfc7,551,551,NaN,551,"LEE PUI YING, YENDY",李佩瑩,Arborist,AR05,32,pylee@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,19
20,ed8dedd0-32bc-4781-8757-97a7f3f1a914,4123,4123,NaN,4123,YEUNG Sheung Lam,NaN,Arborist,YEUNGSHEUNGLAM,32,NaN,1794,12/06/2024 15:59,01/14/2025 11:34,Y,30
21,520ca2da-5805-4ddf-ac9e-9cff01b74b6d,4120,4120,NaN,4120,CHEUNG Chun,NaN,Arborist,CHEUNGCHUN,32,NaN,1794,12/06/2024 15:58,01/14/2025 11:34,Y,6
22,3a3daad9-a0ce-4a21-b0b5-9d5ef0608eb2,4042,4042,NaN,4042,LIU TSZ HONG,廖梓航,Assistant Arborist,AA13,32,thliu@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,20
23,904a7710-db77-49ca-88d2-a12383d63b68,4047,4047,NaN,4047,YEUNG TSZ CHING,楊芷澄,Arborist,YEUNGTSZCHING,32,joyce.lau@baguio.com.hk,1794,12/06/2024 15:59,01/14/2025 11:34,Y,31
24,f4d9c53b-a02f-43a3-9179-a5d8fc94fd74,1833,1833,NaN,1833,"TSUI, JONATHAN SHEK LUN",崔錫倫,Arborist,AR09,32,sltsui@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,23
25,edbe7f22-7796-454f-93c1-a70784f7a862,4078,4078,NaN,4078,CHEUNG Man Ho,NaN,Arborist,CHEUNGMANHO,32,peter.wong@beguio.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,7
26,f58ff731-a9ec-42ee-814c-b5f4d4b28760,4045,4045,NaN,4045,HAI SIU KI,奚笑琪,Arborist,HAISIUKI,32,kay.hai@baguio.com.hk,1794,12/06/2024 15:59,01/14/2025 11:34,Y,12
27,18435724-ef18-4a31-874d-c22f4269900b,4186,4186,NaN,4186,Yau Ka Lim,NaN,Arborist,YAUKALIM,32,NaN,1794,01/06/2025 13:59,01/14/2025 11:34,Y,28
28,374a1156-6b24-4281-ae83-c3b7b6bc5047,4041,4041,NaN,4041,WONG WAN CHI,黃韻諮,Arborist,AR11,32,wcwong@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,26
29,7d790856-1ba1-4f22-90f7-ce26a0081e71,4043,4043,NaN,4043,CHAN CHUEN KIU,陳泉橋,Assistant Arborist,AA14,32,chanchuenkiu@sy12hy19.com.hk,1794,12/06/2024 15:58,01/14/2025 11:34,Y,1
30,117033dd-caf0-4be9-b3b7-dee4d99d8cda,4050,4050,NaN,4050,TSOI Ho Fung,蔡可豐,Arborist,TSOIHOFUNG,32,htfung@winghoyuen.com,1794,12/06/2024 15:59,01/14/2025 11:34,Y,22
31,2902076d-de6a-48ee-991d-e8aacdaf4e02,1721,1721,NaN,1721,HO CHAK KONG,何澤江,Tree Specialist,TS04,32,ckho@sy12hy19.com.hk,1794,12/06/2024 15:59,01/14/2025 11:34,Y,13

In [ ]:
df_f2basicAll['form2.InspectionOfficerFullName']

0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
0    TS04-HO CHAK KONG(Tree Specialist),ckho@sy12hy...
Name: form2.InspectionOfficerFullName, dtype: object

### inspector GUID

In [ ]:
df_f2basicAll[['form2.InspectionOfficerGUID']].iloc[0,0]

'2902076d-de6a-48ee-991d-e8aacdaf4e02'

In [ ]:
###=======================================================================###

# Meta

# Read CSVtoMasterValue json

In [ ]:
jsondata = r'C:\TMCP\CSVToMasterValue.json'

pathlist = str(Path(jsondata).parent)
pathlist

with open(jsondata) as f:
    json_data = f.read()
    data = json.loads(json_data)
    #print(data)
    df_csv = pd.json_normalize(data)

df_csv['link'] = pathlist + '\\' +df_csv['FileName']
df_csv.head()

,FileName,MasterType,IsSystem,link
0,TBL_ADVANCED_ASSESSMENT.csv,AdvancedAssessment,false,C:\TMCP\TBL_ADVANCED_ASSESSMENT.csv
1,TBL_ASPECT.csv,Aspect,false,C:\TMCP\TBL_ASPECT.csv
2,TBL_AUDITOR.csv,,false,C:\TMCP\TBL_AUDITOR.csv
3,TBL_CONTRACT.csv,,False,C:\TMCP\TBL_CONTRACT.csv
4,TBL_CROWN_DENSITY_PERCENT.csv,CrownDensityD,false,C:\TMCP\TBL_CROWN_DENSITY_PERCENT.csv

# Read Version and Mapping

In [ ]:
jsondata = r'C:\Users\ckho\Desktop\tmcp\VersionAndMapping.json'

with open(jsondata) as f:
    json_data = f.read()
    data = json.loads(json_data)
    print(data)
    df_summary = pd.json_normalize(data)

df_dbmasterValue = pd.json_normalize(data, record_path = ['masterValueList'])
df_dbmasterValue.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ckho\\Desktop\\tmcp\\VersionAndMapping.json'

In [ ]:
#cb clickbox
df_decode1 = df_dbmasterValue[df_dbmasterValue.Code.str.startswith('cb')]
df_decode1 = df_decode1.rename(columns={"Code": "Result", "MasterTypeCode": "Code"})
df_decode1

In [ ]:
#form2.SoilCrackOrCrackBehindLean
#form2.Status

otherlist = ['SCOrCBLean','Status']

df_decode2 = df_dbmasterValue[(df_dbmasterValue.MasterTypeCode.isin(otherlist))]
df_decode2 = df_decode2.rename(columns={"Code": "Result", "MasterTypeCode": "Code"})
df_decode2.head()

In [ ]:
df_dbmasterValue.head()

In [ ]:
df_summary.head()

# Merge TwoDataset

In [ ]:
dflink = pd.merge(df_dbmasterValue,df_csv, left_on='MasterTypeCode', right_on='MasterType')
#dflink['Code'].astype(str)
dflink.head()

# Decoding Mapping and Version 'Result Column'

In [ ]:
tmcppath = r'C:\TMCP\CSVUnZIPTemp'

#create dataframe blank in dic
d=None
d={}

path = pathlib.Path(tmcppath)
files = path.glob("**/TBL*.csv")

#codetablelist
for i in files:
    d[i.stem + i.suffix] = pd.read_csv(i, sep='\t')
d.keys()

## Decoding

In [ ]:
resultlist = []
for index, row in dflink.iterrows():
    #print(row['Code'])
    selectData = [int(row['Code'])]
    #print(d[row["FileName"]])
    dfa = d[row["FileName"]]
    dfacode = d[row["FileName"]]['CSV_CODE']
    result = dfa[(dfacode.isin(selectData))].iloc[0,3]
    resultlist.append(result)
    #df2[(df2['ID'].isin(df1['ID']))]

dflink['Result'] = resultlist

dflink = pd.concat([dflink, df_decode1, df_decode2], ignore_index=True)
dflink

# Read F2 json and Decoding

In [ ]:
jsondata = r'C:\Users\ckho\Desktop\tmcp\RTR0015158_11SW-B-R732_1_20240517.json'

with open(jsondata, encoding="utf-8") as f:
    json_data = f.read()
    data = json.loads(json_data)
    #print(data)
    df_summary = pd.json_normalize(data)

In [ ]:
# empty df
df_f2basicAll = []

## Section Basic infomation

In [ ]:
f2basiclist =  df_summary.columns.to_list()[18:]
#f2basiclist

In [ ]:
df_f2basic = df_summary[f2basiclist].replace(dflink.ID.tolist(),  dflink.Result.tolist())
df_f2basic

### concat, change df_f2basicAll to pandas

In [ ]:
TreeID = df_f2basic['form2.DEPTTreeID'].iloc[0]
TreeID

In [ ]:
count = 0
if count == 0:
    df_f2basicAll = pd.DataFrame(columns = df_f2basic.columns.tolist())
df_f2basicAll = pd.concat([df_f2basicAll, df_f2basic])
df_f2basicAll

In [ ]:
#df_f2basic.columns.to_list()

In [ ]:
#df_f2basic.to_excel(r'C:\Users\ckho\Desktop\tmcp\basic.xlsx')

## Section csv

In [ ]:
num = 0

#create dataframe blank in dic
d = None
d = {}
dall = None
dall = {}

f2sectionlist = df_summary.columns.to_list()[0:17]

#codetablelist
for i in f2sectionlist:
    d[i] = pd.json_normalize(data, record_path = [i])
    d[i]['TreeID']=TreeID

    #print(num)

    ###Decoding
    d[i] = d[i].replace(dflink.ID.tolist(),  dflink.Result.tolist())

    #Append gp
    if num == 0:
        dall[i] = pd.DataFrame(columns = d[i].columns.tolist())
    dall[i] = pd.concat([dall[i],d[i]])

num = num +1
d.keys()
dall.keys()